### PR TITLE
Only condense own team if to many pokemon are displayed

### PR DESCRIPTION
**Pull request by sirzento**
This will still let you know all the enemy infos and just condense your own team since you should know the info from your own team.

grafik

### CODE REVIEW

**Comment by Eruyome** [comment]
I could just add that but do you need to see the enemy IVs?
I'd rather rework it to remove enemy ivs and cram the abilities in somewhere.
Then expand ally pokemon, especially now that I implemented this (movesets).
image

**Comment by sirzento** [comment]
Sure thats also ok. This was just an suggestion to only collapse the own team if the space is to small because it would be better than to just collapse everything.

Yours works to. I like that you can see all the moves now. How would you handle it if there are 12 pokemon in battle? Collaps only the enemy? Would work to and I think seeing all own moves is better than seeing enemy trainer IV's.


Btw did you find out if it's only on my side that sometimes I can't see my own team or the enemy trainer team? (latest chrome version)

**Comment by Eruyome** [comment]
Depends on what situation you're in when that happens. For example, there are still some issues with getting the correct identifiers to make calls to pokeapi, devingearing started on something to finally fix that. But what happens is that you might encounter a pokemon that will throw some errors that aren't caught properly, which then breaks the extension for at least the battle that you're in currently. In my endless run I'm facing Tornadus, one of the cases where it breaks. Can't tell you which other pokemon are affected atm.

So, you'd have to describe in more details.

Edit: I would collapse the enemy team.

**Comment by sirzento** [comment]
Ohh okey could be because I had Landorus in my team and the extension never loaded my team. Strangly, the original extension does load it.

Do you know if it is possible to fix the type if the pokemon has an tera shard? The extension still uses the original type

**Comment by Eruyome** [comment]
Oh I'm sure that can be fixed, I thought of that myself yesterday, wondering if the extension even accounts for that at all atm. Haven't looked into it so far.

**Comment by Eruyome** [comment]
The new type effectiveness display doesn't work well in the condensed view that you get with more than 8 pokemon in battle.
It's already fixed but not pushed yet.

**Comment by sirzento** [comment]
Should it look like this?

grafik

**Comment by XDboy500** [comment]
Hello guys, I really like your  work. @sirzento it also looks like this on my pc

**Comment by Eruyome** [comment]
No, it should not...
What browser are you using?
This is how it looks like for me
image

**Comment by sirzento** [comment]
Chrome latest version (Version 125.0.6422.113) but to be real I think it looked better before where each effectiveness had its own row

**Comment by Eruyome** [comment]
I agree to it looking better. But it wasn't or isn't compact enough, at least in some cases where many pokemon in the battle have a high number of weaknesses/resists and immunities.
If I can't quickly figure this out I'll probably add it as an option and make it not the default. Or maybe I should do that anyways.

**Comment by sirzento** [comment]
I mean it was actually fine. It's only some pokemon that have that many weaknesses etc where you need an second row. But even, it only takes like a 1cm more space if you have such pokemon. If you somehow run with a full steal team then yes you maybe lose a complete row but nobody does this.


There are also many timer errors and images that don't load
grafik

**Comment by Eruyome** [comment]
Do me a favour, start a new run with 3 pokemon. Choose Bulbasaur, Charmander and Squirtle. In that order.
Like the picture. I'm already seeing some styling issues here, small ones.

Show me how it looks for you. If you have enough experience with css, maybe see if you can find an issue by fiddling around with the inspector and changing css.

I'm aware of the image stuff, that's unrelated.
I ran into that issue yesterday, where half of my 6th pokemon was cut off.
image

**Comment by Eruyome** [comment]
Can you test if it looks right when you play on 2.0x side bar scale? After changing my scale it also breaks.
Or in general, test some different scales and see if it's right with some and not with others,

**Comment by XDboy500** [comment]
image
It looks like this for me

**Comment by sirzento** [comment]
Ohh ok I got what is the error here. You are using an 1920x1080 monitor right?

### **1080p:**
1080p

### **1440p:**
1440p

### **1440p Ultrawide:**
1440p ultrawide


### **1440p with 2.0x scaling:**
grafik

**Comment by Eruyome** [comment]
I am on a 1080p monitor. I guess the css flex isn't behaving like I thought it would.
I wanted this "snaking" behavior, with the categories flowing in a snake/s-form from left to to right and back.

Anyways, this issue is solved with a single line of css.

Adding this width rule to this selector
```
.roguedex-sidebar .pokemon-type-effectiveness-wrapper.compact .type-effectiveness-block {
    width: fit-content;
}
```

If anyone wants to fix it themselves before I push anything. Don't want to make a commit just for this, I might push something more today still.

**Comment by sirzento** [comment]
Yeah with that it works

### **1440p:**
grafik

### **1440p ultrawide:**
grafik

**Comment by sirzento** [comment]
Still like the design before more :D

**Comment by Eruyome** [comment]
I'll add both, via options. Right now with limited time and manpower I'd rather make it work well on my setup (which I think is a reasonable target) than trying to fully optimize it for all sizes. And I needed something that can be more compact.

**Comment by Eruyome** [comment]
Pushed my fix along with having the new compact view added as a non-default option.

**Comment by sirzento** [comment]
Some Pokemon doesn't even load now. I think you broke something :D
grafik

**Comment by sirzento** [comment]
Stance change has japanese text somehow. Mummy too.
grafik

**Comment by Eruyome** [comment]
I know that some of the "fixes" caused other issues. Some abilities have been using the wrong language for a long time.
I just pushed bigger changes, switched from trying to get the data via constant requests to pokeapi to using included data files. That should work a lot better, but needs a lot of testing, there's too many pokemon out there.

**Comment by sirzento** [comment]
I have something in my team that crashes the whole extension.. Edit: ok now its working again. Idk why it didn't work even after refreshing the browser two times
grafik

German names but you see the icons
grafik

**Pull request closed without merging**
